# https://github.com/actions/runner-images
# https://docs.github.com/en/actions/concepts/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
name: runners
on: push

jobs:
  # Linux
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}

  ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}

  ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}

  # Windows
  windows-latest:
    runs-on: windows-latest
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}

  windows-2025:
    runs-on: windows-2025
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}

  windows-2022:
    runs-on: windows-2022
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}

  # macOS
  macos-latest:
    runs-on: macos-latest
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}

  macos-15:
    runs-on: macos-15
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}

  macos-14:
    runs-on: macos-14
    steps:
      - run: echo $RUNNER_OS # ${{ runner.os }}
