# https://docs.github.com/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets
name: secrets
on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          echo $GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mask secret
        run: |
          SECRET=secret
          echo "::add-mask::$SECRET"
          echo $SECRET
